import "./globals.css";
import { type Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import Providers from "./providers";
import { cn } from "@/lib/utils";
import AppNavigation from "@/components/AppNavigation";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Occtoo Boilerplate Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <AppNavigation />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
